version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: php-docker
    ports:
      - 8080:80
    volumes:
      - ./www/:/www
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: php_docker
      DB_USERNAME: test
      DB_PASSWORD: password
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: php_docker
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password